### ISSUE TITLE
It seems that av1 compression is not supported

### ISSUE THREAD

**Issue by faradaytrs** [zoellner/sharp-heic-lambda-layer#32]
When i try to generate avif image with sharp (which is basically just heif with av1 compression) i get:
Error: heifsave: Unsupported compression

**Comment by faradaytrs** [comment]
It seems that libaom is disabled, why?

**Comment by chriswritests** [comment]
I'm experiencing the same issue, any ideas @zoellner ?

**Comment by zoellner** [comment]
I attempted to add it at some point but the build wasn't stable. I forgot what the issue was.
Since I don't need the support for my projects it's not a priority for me but if you want to create a PR that produces a stable build with libaom I'm happy to include it. 
Please include some instructions/example code for me to test it.

**Comment by faradaytrs** [comment]
@zoellner I actually solved it for myself, https://github.com/faradaytrs/sharp-heic-lambda-layer/blob/main/sample-buildproject.yaml
What do you mean build was unstable? I use this version in production right now and it's absolutely stable.

**Comment by faradaytrs** [comment]
> I'm experiencing the same issue, any ideas @zoellner ?

you can build from my fork https://github.com/faradaytrs/sharp-heic-lambda-layer/

**Comment by faradaytrs** [comment]
I also tried to replace aom with dav1d+rav1e, I got a working build, but it happened to be slower than libaom on real data and picture was larger.
